const todoConstant = {
    TODO_REQUEST: "TODO_REQUEST",
    TODO_RESPONCE: "TODO_SUCCESS",
    TODO_RECEIVE: "TODO_RECEIVE",
    TODO_ERORR: "TODO_ERROR",
    TODO_SET_DATA: "TODO_SET_DATA",
    TODO_RESET_DATA: "TODO_RESET_DATA"
}

export default todoConstant